sudo: required

dist: trusty 

services:
    - docker 

language: cpp

matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      env:
         - MATRIX_EVAL="docker run -td --name zetavm zetavm/testing"

    # works on Precise and Trusty
    - os: linux
      env:
         - MATRIX_EVAL="docker run -td --name zetavm -e CXX=clang++ zetavm/testing"

install:
    - docker build -t zetavm/testing .
    - eval "${MATRIX_EVAL}"

script:
    - docker exec zetavm ./configure
    - docker exec zetavm make
    - docker exec zetavm make test

